### ISSUE TITLE
Opening display settings with pt_BR lang closes the settings app

### ISSUE THREAD

**Issue by sobrinho** [TinkerBoard/android-7.1.2_kernel#10]
Every time I try to open Settings > Display using Português Brasil language, it closes.

logcat output:

```
11-20 17:32:46.873  4555  4576 W ProcStatsManager: No process com.android.bluetooth/1002 for service com.android.bluetooth.a2dp.A2dpService
11-20 17:32:46.873  4555  4576 W ProcStatsManager: No process com.android.bluetooth/1002 for service com.android.bluetooth.hfp.HeadsetService
11-20 17:32:46.873  4555  4576 W ProcStatsManager: No process com.android.bluetooth/1002 for service com.android.bluetooth.opp.BluetoothOppService
11-20 17:32:46.873  4555  4576 W ProcStatsManager: No process com.android.bluetooth/1002 for service com.android.bluetooth.pan.PanService
11-20 17:32:46.873  4555  4576 W ProcStatsManager: No process com.android.bluetooth/1002 for service com.android.bluetooth.hid.HidService
11-20 17:32:46.874  4555  4576 W ProcStatsManager: No process com.android.bluetooth/1002 for service com.android.bluetooth.btservice.AdapterService
11-20 17:32:46.874  4555  4576 W ProcStatsManager: No process com.android.bluetooth/1002 for service com.android.bluetooth.gatt.GattService
11-20 17:32:46.874  4555  4576 W ProcStatsManager: No process android.process.acore/10001 for service com.android.providers.contacts.VoicemailCleanupService
11-20 17:32:46.892   235   259 I [Gralloc]: Got fd 39 for handle 10
11-20 17:32:46.893   235   259 I [Gralloc]: leave, w : 1280, h : 720, format : 0x1,internal_format : 0x1, usage : 0xb00. size=3686400,pixel_stride=1280,byte_stride=5120
11-20 17:32:46.893   235   259 I [Gralloc]: leave: prime_fd=39,share_attr_fd=73
11-20 17:32:46.900  4555  4573 I [Gralloc]: Got handle 4 for fd 70
11-20 17:32:46.900  4555  4573 I [Gralloc]: leave, w : 1280, h : 720, format : 0x1,internal_format : 0x1, usage : 0xb00. size=3686400,pixel_stride=1280,byte_stride=5120
11-20 17:32:46.900  4555  4573 I [Gralloc]: leave: prime_fd=70,share_attr_fd=71
11-20 17:32:46.902  4555  4555 D HeadsetProfile: Bluetooth service connected
11-20 17:32:46.943   235   259 I [Gralloc]: Got fd 47 for handle 8
11-20 17:32:46.943   235   259 I [Gralloc]: leave, w : 1280, h : 720, format : 0x1,internal_format : 0x1, usage : 0xb00. size=3686400,pixel_stride=1280,byte_stride=5120
11-20 17:32:46.943   235   259 I [Gralloc]: leave: prime_fd=47,share_attr_fd=63
11-20 17:32:46.945  4555  4573 I [Gralloc]: Got handle 5 for fd 72
11-20 17:32:46.946  4555  4573 I [Gralloc]: leave, w : 1280, h : 720, format : 0x1,internal_format : 0x1, usage : 0xb00. size=3686400,pixel_stride=1280,byte_stride=5120
11-20 17:32:46.946  4555  4573 I [Gralloc]: leave: prime_fd=72,share_attr_fd=73
11-20 17:32:48.219  1366  1366 I GeofencerStateMachine: sendNewTransitions called.
11-20 17:32:51.725  1624  4162 I CastDatabase: Saving the database
11-20 17:32:51.737  1624  4162 E SQLiteCastStore: Skip saving CastDeviceInfo: "Dispositivo próximo" (__cast_nearby___V_520d1f2e-c90a-4b4f-b9da-daa1adbadbac)
11-20 17:32:51.738  1624  4162 I SQLiteCastStore: [CastNetworkInfo] saved: 0, skipped: 0, [CastDeviceInfo]: saved 0, skipped 1, Paired Guest Mode DeviceInfo] saved: 0, skipped: 0. [ProbedNetworks]: saved 0, skipped: 0, [ProbedSocketAddress]: saved 0, skipped: 0
11-20 17:32:54.194  1366  1366 I GeofencerStateMachine: sendNewTransitions called.
11-20 17:32:54.646   666  2845 I ActivityManager: START u0 {flg=0x8000 cmp=com.android.settings/.Settings$DisplaySettingsActivity (has extras)} from uid 1000 on display 0
11-20 17:32:54.707   666  4551 E UserRestrictionsUtils: Unknown restriction: null
11-20 17:32:54.709   666  4551 E UserRestrictionsUtils: Unknown restriction: null
11-20 17:32:54.807  4555  4572 D Index   : Indexing locale 'pt_BR' took 6 millis
11-20 17:32:54.817   666  2845 W DreamManagerService: Dream ComponentInfo{com.google.android.deskclock/com.android.deskclock.Screensaver} does not exist
11-20 17:32:54.817   666  2845 W DreamManagerService: Falling back to default dream ComponentInfo{com.google.android.deskclock/com.android.deskclock.Screensaver}
11-20 17:32:54.826  4555  4555 D AndroidRuntime: Shutting down VM
11-20 17:32:54.827  4555  4555 E AndroidRuntime: FATAL EXCEPTION: main
11-20 17:32:54.827  4555  4555 E AndroidRuntime: Process: com.android.settings, PID: 4555
11-20 17:32:54.827  4555  4555 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.android.settings/com.android.settings.Settings$DisplaySettingsActivity}: java.lang.ArrayIndexOutOfBoundsException: length=7; index=7
11-20 17:32:54.827  4555  4555 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3435)
11-20 17:32:54.827  4555  4555 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3475)
11-20 17:32:54.827  4555  4555 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2738)
11-20 17:32:54.827  4555  4555 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
11-20 17:32:54.827  4555  4555 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1483)
11-20 17:32:54.827  4555  4555 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-20 17:32:54.827  4555  4555 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
11-20 17:32:54.827  4555  4555 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6141)
11-20 17:32:54.827  4555  4555 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-20 17:32:54.827  4555  4555 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
11-20 17:32:54.827  4555  4555 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
11-20 17:32:54.827  4555  4555 E AndroidRuntime: Caused by: java.lang.ArrayIndexOutOfBoundsException: length=7; index=7
11-20 17:32:54.827  4555  4555 E AndroidRuntime: 	at com.android.settings.DisplaySettings.updateTimeoutPreferenceDescription(DisplaySettings.java:320)
11-20 17:32:54.827  4555  4555 E AndroidRuntime: 	at com.android.settings.DisplaySettings.onResume(DisplaySettings.java:347)
11-20 17:32:54.827  4555  4555 E AndroidRuntime: 	at android.app.Fragment.performResume(Fragment.java:2399)
11-20 17:32:54.827  4555  4555 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1032)
11-20 17:32:54.827  4555  4555 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
11-20 17:32:54.827  4555  4555 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
11-20 17:32:54.827  4555  4555 E AndroidRuntime: 	at android.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:2049)
11-20 17:32:54.827  4555  4555 E AndroidRuntime: 	at android.app.FragmentController.dispatchResume(FragmentController.java:198)
11-20 17:32:54.827  4555  4555 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:6834)
11-20 17:32:54.827  4555  4555 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3412)
11-20 17:32:54.827  4555  4555 E AndroidRuntime: 	... 10 more
11-20 17:32:54.832   666  4551 W ActivityManager:   Force finishing activity com.android.settings/.Settings$DisplaySettingsActivity
11-20 17:32:54.838   666  4551 W ActivityManager:   Force finishing activity com.android.settings/.Settings
11-20 17:32:54.841  4555  4572 D Index   : Indexing locale 'pt_BR' took 25 millis
11-20 17:32:54.897   666  4408 I OpenGLRenderer: Initialized EGL, version 1.4
11-20 17:32:54.897   666  4408 D OpenGLRenderer: Swap behavior 1
11-20 17:32:54.903   235   261 I [Gralloc]: Got fd 100 for handle 6
11-20 17:32:54.904   235   261 I [Gralloc]: leave, w : 760, h : 391, format : 0x1,internal_format : 0x1, usage : 0x900. size=1201152,pixel_stride=768,byte_stride=3072
11-20 17:32:54.904   235   261 I [Gralloc]: leave: prime_fd=100,share_attr_fd=119
11-20 17:32:54.906   235   261 I [Gralloc]: Got fd 140 for handle 9
11-20 17:32:54.907   235   261 I [Gralloc]: leave, w : 760, h : 391, format : 0x1,internal_format : 0x1, usage : 0x900. size=1201152,pixel_stride=768,byte_stride=3072
11-20 17:32:54.907   235   261 I [Gralloc]: leave: prime_fd=140,share_attr_fd=146
11-20 17:32:54.910   235   261 I [Gralloc]: Got fd 151 for handle 13
11-20 17:32:54.910   235   261 I [Gralloc]: leave, w : 760, h : 391, format : 0x1,internal_format : 0x1, usage : 0x900. size=1201152,pixel_stride=768,byte_stride=3072
11-20 17:32:54.910   235   261 I [Gralloc]: leave: prime_fd=151,share_attr_fd=77
11-20 17:32:54.912   235   261 I [Gralloc]: Got fd 163 for handle 18
11-20 17:32:54.912   235   261 I [Gralloc]: leave, w : 760, h : 391, format : 0x1,internal_format : 0x1, usage : 0x900. size=1201152,pixel_stride=768,byte_stride=3072
11-20 17:32:54.913   235   261 I [Gralloc]: leave: prime_fd=163,share_attr_fd=56
11-20 17:32:54.915   666  4408 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
11-20 17:32:54.927   235   261 I [Gralloc]: Got fd 56 for handle 18
11-20 17:32:54.928   235   261 I [Gralloc]: leave, w : 760, h : 391, format : 0x1,internal_format : 0x1, usage : 0xb00. size=1201152,pixel_stride=768,byte_stride=3072
11-20 17:32:54.928   235   261 I [Gralloc]: leave: prime_fd=56,share_attr_fd=98
11-20 17:32:54.929   666  4408 I [Gralloc]: Got handle 2 for fd 292
11-20 17:32:54.929   666  4408 I [Gralloc]: leave, w : 760, h : 391, format : 0x1,internal_format : 0x1, usage : 0xb00. size=1201152,pixel_stride=768,byte_stride=3072
11-20 17:32:54.929   666  4408 I [Gralloc]: leave: prime_fd=292,share_attr_fd=293
11-20 17:32:54.942   235   261 I [Gralloc]: Got fd 77 for handle 13
11-20 17:32:54.943   235   261 I [Gralloc]: leave, w : 760, h : 391, format : 0x1,internal_format : 0x1, usage : 0xb00. size=1201152,pixel_stride=768,byte_stride=3072
11-20 17:32:54.943   235   261 I [Gralloc]: leave: prime_fd=77,share_attr_fd=143
11-20 17:32:54.943   666  4408 I [Gralloc]: Got handle 3 for fd 298
11-20 17:32:54.945   666  4408 I [Gralloc]: leave, w : 760, h : 391, format : 0x1,internal_format : 0x1, usage : 0xb00. size=1201152,pixel_stride=768,byte_stride=3072
11-20 17:32:54.945   666  4408 I [Gralloc]: leave: prime_fd=298,share_attr_fd=300
11-20 17:32:54.957   235   259 I [Gralloc]: Got fd 122 for handle 9
11-20 17:32:54.958   235   259 I [Gralloc]: leave, w : 760, h : 391, format : 0x1,internal_format : 0x1, usage : 0xb00. size=1201152,pixel_stride=768,byte_stride=3072
11-20 17:32:54.958   235   259 I [Gralloc]: leave: prime_fd=122,share_attr_fd=140
11-20 17:32:54.961   666  4408 I [Gralloc]: Got handle 4 for fd 297
11-20 17:32:54.961   666  4408 I [Gralloc]: leave, w : 760, h : 391, format : 0x1,internal_format : 0x1, usage : 0xb00. size=1201152,pixel_stride=768,byte_stride=3072
11-20 17:32:54.961   666  4408 I [Gralloc]: leave: prime_fd=297,share_attr_fd=301
11-20 17:32:55.338   666   698 W ActivityManager: Activity pause timeout for ActivityRecord{b49959e u0 com.android.settings/.Settings$DisplaySettingsActivity t161 f}
11-20 17:32:55.344   666   698 W WindowManager: Forcing App on portrait mode, do not rotate
11-20 17:32:55.345   666  2719 W WindowManager: Forcing App on portrait mode, do not rotate
11-20 17:32:55.403   666  2719 W WindowManager: Forcing App on portrait mode, do not rotate
11-20 17:32:55.422   235   259 I [Gralloc]: Got fd 78 for handle 23
11-20 17:32:55.423   235   259 I [Gralloc]: leave, w : 1280, h : 720, format : 0x1,internal_format : 0x1, usage : 0x900. size=3686400,pixel_stride=1280,byte_stride=5120
11-20 17:32:55.423   235   259 I [Gralloc]: leave: prime_fd=78,share_attr_fd=112
11-20 17:32:55.432   235   259 I [Gralloc]: Got fd 149 for handle 24
11-20 17:32:55.433   235   259 I [Gralloc]: leave, w : 1280, h : 720, format : 0x1,internal_format : 0x1, usage : 0x900. size=3686400,pixel_stride=1280,byte_stride=5120
11-20 17:32:55.433   235   259 I [Gralloc]: leave: prime_fd=149,share_attr_fd=157
11-20 17:32:55.441   235   259 I [Gralloc]: Got fd 135 for handle 25
11-20 17:32:55.442   235   259 I [Gralloc]: leave, w : 1280, h : 720, format : 0x1,internal_format : 0x1, usage : 0x900. size=3686400,pixel_stride=1280,byte_stride=5120
11-20 17:32:55.442   235   259 I [Gralloc]: leave: prime_fd=135,share_attr_fd=136
11-20 17:32:55.450   235   259 I [Gralloc]: Got fd 124 for handle 26
11-20 17:32:55.451   235   259 I [Gralloc]: leave, w : 1280, h : 720, format : 0x1,internal_format : 0x1, usage : 0x900. size=3686400,pixel_stride=1280,byte_stride=5120
11-20 17:32:55.451   235   259 I [Gralloc]: leave: prime_fd=124,share_attr_fd=128
11-20 17:32:55.452  1280  1380 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
11-20 17:32:55.484   235   261 I [Gralloc]: Got fd 115 for handle 26
11-20 17:32:55.486   235   261 I [Gralloc]: leave, w : 1280, h : 720, format : 0x1,internal_format : 0x1, usage : 0xb00. size=3686400,pixel_stride=1280,byte_stride=5120
11-20 17:32:55.486   235   261 I [Gralloc]: leave: prime_fd=115,share_attr_fd=146
11-20 17:32:55.486  1280  1380 I [Gralloc]: Got handle 2 for fd 59
11-20 17:32:55.486  1280  1380 I [Gralloc]: leave, w : 1280, h : 720, format : 0x1,internal_format : 0x1, usage : 0xb00. size=3686400,pixel_stride=1280,byte_stride=5120
11-20 17:32:55.486  1280  1380 I [Gralloc]: leave: prime_fd=59,share_attr_fd=60
11-20 17:32:55.507   235   259 I [Gralloc]: Got fd 89 for handle 25
11-20 17:32:55.508   235   259 I [Gralloc]: leave, w : 1280, h : 720, format : 0x1,internal_format : 0x1, usage : 0xb00. size=3686400,pixel_stride=1280,byte_stride=5120
11-20 17:32:55.508   235   259 I [Gralloc]: leave: prime_fd=89,share_attr_fd=131
11-20 17:32:55.509  1280  1380 I [Gralloc]: Got handle 3 for fd 61
11-20 17:32:55.509  1280  1380 I [Gralloc]: leave, w : 1280, h : 720, format : 0x1,internal_format : 0x1, usage : 0xb00. size=3686400,pixel_stride=1280,byte_stride=5120
11-20 17:32:55.509  1280  1380 I [Gralloc]: leave: prime_fd=61,share_attr_fd=62
11-20 17:32:55.533   666   722 W WindowManager: Forcing App on portrait mode, do not rotate
11-20 17:32:55.978  1280  1380 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
11-20 17:32:55.996   235   378 I [Gralloc]: Got fd 139 for handle 24
11-20 17:32:55.997   235   378 I [Gralloc]: leave, w : 1280, h : 720, format : 0x1,internal_format : 0x1, usage : 0xb00. size=3686400,pixel_stride=1280,byte_stride=5120
11-20 17:32:55.997   235   378 I [Gralloc]: leave: prime_fd=139,share_attr_fd=133
11-20 17:32:55.997  1280  1380 I [Gralloc]: Got handle 4 for fd 63
11-20 17:32:55.997  1280  1380 I [Gralloc]: leave, w : 1280, h : 720, format : 0x1,internal_format : 0x1, usage : 0xb00. size=3686400,pixel_stride=1280,byte_stride=5120
11-20 17:32:55.997  1280  1380 I [Gralloc]: leave: prime_fd=63,share_attr_fd=64
11-20 17:32:59.263  1366  1366 I GeofencerStateMachine: sendNewTransitions called.
11-20 17:32:59.732   666   756 D WifiStateMachine: updateCapabilities for config:Bodefalse,false
11-20 17:32:59.732   666   760 D ConnectivityService: notifyType CAP_CHANGED for NetworkAgentInfo [WIFI () - 100]
11-20 17:32:59.732   666   760 D ConnectivityService:  sending notification for NetworkRequest [ REQUEST id=1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ]
```

**Comment by jamess-huang** [comment]
thanks for your feedback , we will check this.

**Comment by jamess-huang** [comment]
Please cherry-pick this change
https://bitbucket.org/TinkerBoard_Android/packages-apps-settings/commits/f20a6824ed05c00675e36812cc06594ca34d0032

**Comment by sobrinho** [comment]
Great, it fixed!

The never sleep string is in English but that's fine for me.

Thanks!
